# --- Sparse Attention config ---
[solution]
name = "dogacel-agent-solution-sparse-attention-v3"
definition = "dsa_sparse_attention_h16_ckv512_kpe64_topk2048_ps64"
author = "Doğaç Eldenk"

[build]
language = "triton"
source_dir = "triton"
entry_point = "sparse_fused.py::kernel"
